[package]
name = "print-tray-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printers = "1.2.0"
tokio = "1.28.1"
warp = "0.3.5"
